version: "3.8"

services:
  # PHP Laravel CLI Container
  cli:
    build:
      context: cli
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ..:/workspaces/autoaff:cached
      - ./ssh:/home/user/.ssh
      - ./cli/cron:/etc/periodic/1min
    ports:
      - "8000:8000"
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - devcontainer-network
    depends_on:
      - db
      - redis

  # MariaDB Database
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 'example'
      MARIADB_DATABASE: 'autoaff'
      MARIADB_USER: 'laravel'
      MARIADB_PASSWORD: 'example'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - devcontainer-network
  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - devcontainer-network
  # Adminer Database GUI
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - devcontainer-network

networks:
  devcontainer-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
